# Generated by Django 4.2.16 on 2024-11-03 08:44

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0209_user_show_ratings"),
    ]

    operations = [
        migrations.AddField(
            model_name="edition",
            name="translator",
            field=bookwyrm.models.fields.CharField(
                blank=True, max_length=255, null=True
            ),
        ),
    ]
